name: learning_management_systemo_v01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  dio: ^5.6.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/splash.json
    - assets/images/loginimg.png
